package com.jzheadley.reachout.models.dataobjects;

import android.os.Parcel;
import android.os.Parcelable;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;
import com.jzheadley.reachout.models.services.NessieService;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

@DynamoDBTable(tableName = "ReachOutProposals")
public class Proposal implements Parcelable {
    public static final int STATE_INCOMPLETE = 0;
    public static final int STATE_SUBMITTED_OFFLINE = 1;
    public static final int STATE_SUBMITTED_ONLINE = 2;
    public static final int STATE_FUNDED = 3;
    public static final int STATE_CASH_WITHDRAWN = 4;
    public static final int STATE_CASH_REPAID = 5;
    public static final Creator<Proposal> CREATOR = new Creator<Proposal>() {
        @Override
        public Proposal createFromParcel(Parcel source) {
            return new Proposal(source);
        }

        @Override
        public Proposal[] newArray(int size) {
            return new Proposal[size];
        }
    };
    public String businessDescription = " ";
    public String purchaseDescription = " ";
    public String planDescription = " ";
    public Set<String> pictures = new HashSet<>();
    private Set<String> endorsingLeaders = new HashSet<>();
    private String proposalId = " ";
    private String personId = " ";
    private int state = STATE_INCOMPLETE;
    private int amountBorrowed = -1;
    private int amountToBeRepayed = -1;
    private int monthsOfLoan = -1;
    private String accountNumber = " ";
    private Long dateFunded = 0L;
    private String lenderAccountNumber = " ";
    private Long dateRepaid = 0L; //Actual, not due date
    private NessieService nessieService;

    public Proposal(String proposalId) {
        this.proposalId = proposalId;
    }

    public Proposal() {
        pictures.add(" ");
        endorsingLeaders.add(" ");
    }


    protected Proposal(Parcel in) {
        this.businessDescription = in.readString();
        this.purchaseDescription = in.readString();
        this.planDescription = in.readString();
        this.pictures = new HashSet<String>(in.readArrayList(ArrayList.class.getClassLoader()));
        this.endorsingLeaders = new HashSet<String>(in.readArrayList(ArrayList.class.getClassLoader()));
        this.proposalId = in.readString();
        this.personId = in.readString();
        this.state = in.readInt();
        this.amountBorrowed = in.readInt();
        this.amountToBeRepayed = in.readInt();
        this.monthsOfLoan = in.readInt();
        this.accountNumber = in.readString();
        this.dateFunded = (Long) in.readValue(Long.class.getClassLoader());
        this.lenderAccountNumber = in.readString();
        this.dateRepaid = (Long) in.readValue(Long.class.getClassLoader());
    }

    public void setEndorsingLeaders(Set<String> endorsingLeaders) {
        this.endorsingLeaders = endorsingLeaders;
    }

    public void setPictures(Set<String> pictures) {
        this.pictures = pictures;
    }

    @Override
    public String toString() {
        return "Proposal{" +
            "businessDescription='" + businessDescription + '\'' +
            ", purchaseDescription='" + purchaseDescription + '\'' +
            ", planDescription='" + planDescription + '\'' +
            ", pictures=" + pictures +
            ", endorsingLeaders=" + endorsingLeaders +
            ", proposalId='" + proposalId + '\'' +
            ", personId='" + personId + '\'' +
            ", state=" + state +
            ", amountBorrowed=" + amountBorrowed +
            ", amountToBeRepayed=" + amountToBeRepayed +
            ", monthsOfLoan=" + monthsOfLoan +
            ", accountNumber='" + accountNumber + '\'' +
            ", dateFunded=" + dateFunded +
            ", lenderAccountNumber='" + lenderAccountNumber + '\'' +
            ", dateRepaid=" + dateRepaid +
            '}';
    }

    /* State changes */
    public boolean submit_offline() {
        state = STATE_SUBMITTED_OFFLINE;
        return true;
    }

    public void submitted_online(String accountNumber) {
            state = STATE_SUBMITTED_ONLINE;
            this.accountNumber = accountNumber;
        }


    /* Getters / Setters */
    // @DynamoDBAutoGeneratedKey

    public void funded(String lenderAccountNumber) {
        setLenderAccountNumber(lenderAccountNumber);
        state = STATE_FUNDED;
        this.lenderAccountNumber = lenderAccountNumber;
        this.dateFunded = System.currentTimeMillis();
    }

    public void cashWithdrawn() {
        state = STATE_CASH_WITHDRAWN;
    }

    public void cashRepaid() {
        state = STATE_CASH_REPAID;
        this.dateRepaid = System.currentTimeMillis();
    }

    @DynamoDBHashKey(attributeName = "proposalId")
    public String getProposalId() {
        return proposalId;
    }

    public void setProposalId(String proposalId) {
        this.proposalId = proposalId;
    }

    @DynamoDBAttribute
    public String getPersonId() {
        return personId;
    }

    public void setPersonId(String personId) {
        this.personId = personId;
    }

    @DynamoDBAttribute
    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    @DynamoDBAttribute
    public int getAmountBorrowed() {
        return amountBorrowed;
    }

    public void setAmountBorrowed(int amountBorrowed) {
        this.amountBorrowed = amountBorrowed;
    }

    @DynamoDBAttribute
    public int getAmountToBeRepayed() {
        return amountToBeRepayed;
    }

    public void setAmountToBeRepayed(int amountToBeRepayed) {
        this.amountToBeRepayed = amountToBeRepayed;
    }

    @DynamoDBAttribute
    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    @DynamoDBAttribute
    public int getMonthsOfLoan() {
        return monthsOfLoan;
    }

    public void setMonthsOfLoan(int monthsOfLoan) {
        this.monthsOfLoan = monthsOfLoan;
    }

    @DynamoDBAttribute
    public Long getDateFunded() {
        return dateFunded;
    }

    public void setDateFunded(Long dateFunded) {
        this.dateFunded = dateFunded;
    }

    @DynamoDBAttribute
    public String getLenderAccountNumber() {
        return lenderAccountNumber;
    }

    public void setLenderAccountNumber(String lenderAccountNumber) {
        this.lenderAccountNumber = lenderAccountNumber;
    }

    @DynamoDBAttribute
    public Long getDateRepaid() {
        return dateRepaid;
    }

    public void setDateRepaid(Long dateRepaid) {
        this.dateRepaid = dateRepaid;
    }

    @DynamoDBAttribute
    public String getBusinessDescription() {
        return businessDescription;
    }

    public void setBusinessDescription(String businessDescription) {
        this.businessDescription = businessDescription;
    }

    @DynamoDBAttribute
    public String getPurchaseDescription() {
        return purchaseDescription;
    }

    public void setPurchaseDescription(String purchaseDescription) {
        this.purchaseDescription = purchaseDescription;
    }

    @DynamoDBAttribute
    public String getPlanDescription() {
        return planDescription;
    }

    public void setPlanDescription(String planDescription) {
        this.planDescription = planDescription;
    }

    @DynamoDBAttribute
    public Set<String> getPictures() {
        return pictures;
    }

    public void setPictures(HashSet<String> pictures) {
        this.pictures = pictures;
    }

    @DynamoDBAttribute
    public Set<String> getEndorsingLeaders() {
        return endorsingLeaders;
    }

    public void setEndorsingLeaders(HashSet<String> endorsingLeaders) {
        this.endorsingLeaders = endorsingLeaders;
    }

    @Override
    public int describeContents() {
        return 2;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.businessDescription);
        dest.writeString(this.purchaseDescription);
        dest.writeString(this.planDescription);
        dest.writeList(new ArrayList<String>(this.pictures));
        dest.writeList(new ArrayList<String>(this.endorsingLeaders));
        dest.writeString(this.proposalId);
        dest.writeString(this.personId);
        dest.writeInt(this.state);
        dest.writeInt(this.amountBorrowed);
        dest.writeInt(this.amountToBeRepayed);
        dest.writeInt(this.monthsOfLoan);
        dest.writeString(this.accountNumber);
        dest.writeValue(this.dateFunded);
        dest.writeString(this.lenderAccountNumber);
        dest.writeValue(this.dateRepaid);
    }
}
